# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# default.yml
#
# Use this global manifest (`default.yml`) to configure
# top-level settings for your organization as a whole, and
# controls/reports/etc that apply to all of your fleets.
#
# To see all supported options, check out:
#   • https://fleetdm.com/docs/configuration/yaml-files
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

org_settings:
  fleet_desktop:
    transparency_url: https://catoftheday.com

  host_expiry_settings:
    host_expiry_enabled: true
    host_expiry_window: 30

  org_info:
    org_name: EMBL_EBI

  webhook_settings:
    activities_webhook:
      enable_activities_webhook: true
      destination_url: https://webhook.site/cc0d62ca-ad03-4a1d-99e0-c0d660d84bdb

  server_settings:
    ###########################################################
    # The server URL where Fleet is running.
    ###########################################################
    server_url: $FLEET_URL

  ###########################################################
  # Uncomment to use single sign-on (SSO) for admins accessing Fleet.
  ###########################################################
  # sso_settings:
  #   idp_name: "Okta"
  #   metadata_url: "https://okta.com/replace-this-url"
  #   entity_id: "fleet-admins"

  mdm:
    ###########################################################
    # Uncomment to use SSO for end-user authentication during enrollment
    ###########################################################
    # end_user_authentication:
    #   idp_name: "Okta"
    #   metadata_url: "https://okta.com/replace-this-url"
    #   entity_id: "fleet-end-users"

    ###########################################################
    # Apple Business Manager (ABM)
    ###########################################################
    # apple_business_manager:
    #   - organization_name: "My Company, Inc."
    #     macos_fleet: "💻 Workstations"

    ###########################################################
    # Volume Purchasing Program (VPP)
    ###########################################################
    # volume_purchasing_program:
    #   - location: "My location."
    #     fleets:
    #       - "💻 Workstations"
    #       - "📱🔐 Personal mobile devices"

controls:
  ###########################################################
  # macOS migration settings
  ###########################################################
  # macos_migration:
  #   enable: true
  #   mode: voluntary
  #   webhook_url: "https://example.com/webhook"

  ###########################################################
  # Windows MDM
  ###########################################################
  # windows_enabled_and_configured: true


###########################################################
# Labels
###########################################################
labels:
  - paths: ./labels/*.yml